name: CI

on: 
  schedule:
    - cron: '0 0 * * *'

  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Perf Action
          uses: QAInsights/PerfAction@2.0
          with:
            test-plan-path: './tests//Regular expressions.jmx'
            args: ""

        - name: Upload Results
          uses: actions/upload-artifact@v2
          with: 
            name: jmeter-results
            path: result.jtl


#         - name: Test
#           run: |
#               sh jmeter -n -t "./tests//Regular expressions.jmx"  -l "./Results-csv/results.csv" -e -o "./Reports" 
# #              npm test

#         - name: Upload report artifact
#           uses: actions/upload-artifact@v2
#           with: 
#             name: ${{ github.run_number }}-mochawesome-report-upload
#             path: ./mochawesome-report/
#             if-no-files-found: ignore        


#         - name: Deploy pages
#           uses: peaceiris/actions-gh-pages@v3
#           with:
#               github_token: ${{ secrets.GITHUB_TOKEN }}
#               publish_dir: mochawesome-report   
