# This yml will run the JMeter tests using JMeter thats present within this project repo. 
# Due to memory issues removing the contents of that folder, if we put the jmeter contents in that folder and enable this file it will run as usual.

name: CI

on: 

# schedule:
#   - cron: '0 0 * * *'

  # Triggers the workflow on push or pull request events but only for the "master" branch
 push:
  branches: [ "none" ]
 pull_request:
  branches: [ "none" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - uses: actions/setup-node@v1
          with:
            node-version: 16

        - name: Install
          run: npm install

        - name: Test
          run: |
              ./apache-jmeter-5.5/bin/jmeter -v
              sh ./apache-jmeter-5.5/bin/jmeter -n -t "./tests/Regular expressions.jmx"  -l "./Results-csv/results.csv" -e -o "./Reports" 
#              npm test

        - name: Upload report artifact
          uses: actions/upload-artifact@v2
          with: 
            name: ${{ github.run_number }}-jmeter-report-upload
            path: ./Reports
            if-no-files-found: ignore        


        - name: Deploy pages
          uses: peaceiris/actions-gh-pages@v3
          with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: ./Reports
