name: CI

on: 
#  schedule:
#    - cron: '0 0 * * *'

  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "disable" ]
  pull_request:
    branches: [ "disable" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - uses: actions/setup-node@v1
          with:
            node-version: 16

        - name: Install
          run: npm install

        - name: Test
          run: |
              sh jmeter -n -t "./tests//Regular expressions.jmx"  -l "./Results-csv/results.csv" -e -o "./Reports" 
#              npm test

        - name: Upload report artifact
          uses: actions/upload-artifact@v2
          with: 
            name: ${{ github.run_number }}-mochawesome-report-upload
            path: ./mochawesome-report/
            if-no-files-found: ignore        


        - name: Deploy pages
          uses: peaceiris/actions-gh-pages@v3
          with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: mochawesome-report   
