name: JMeter_run
on:
  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      - uses: actions/checkout@v3
      - name: run jmeter on github action
        uses: sebiboga/run-jmeter-github-action@v0.0.4